#!/bin/bash

pushd () {
    command pushd "$@" > /dev/null
}

popd () {
    command popd "$@" > /dev/null
}

# rm -rf src/*

# pushd src

# git clone https://github.com/starkandwayne/bucc.git
# git clone https://github.com/cloudfoundry/bosh-deployment.git
# git clone https://github.com/cloudfoundry/cf-deployment.git

# popd

REPO_BUCC=$PWD/src/bucc
REPO_BOSH=$PWD/src/bosh-deployment
REPO_CF=$PWD/src/cf-deployment

# echo $REPO_BUCC
# echo $REPO_BOSH
# echo $REPO_CF

# exit

pushd $REPO_BUCC

source .envrc

# create a jq-path alias
# to do this we need to set the "expand_aliases" shell option
# and then define the alias
shopt -s expand_aliases
alias jq-path="jq '[path(..)|map(if type==\"number\" then \"[]\" else tostring end)|join(\".\")|split(\".[]\")|join(\"[]\")]|unique|map(\".\"+.)|.[]'"

certificate_authorities=$(yq read state/cf-deployment-vars.yml -j | jq | jq-path | grep -e '.ca"' | grep -E -v -- '_ca' | sed 's/"//g' | awk '{ gsub("[.]","/",$0); print $0 }' )

for certificate_authority in $certificate_authorities
do
    common_name=$(openssl x509 -in <(bosh interpolate state/cf-deployment-vars.yml --path $certificate_authority) -text -noout | grep -e 'Issuer:' | awk '{ print $5 }')
    fingerprint=$(openssl x509 -noout -fingerprint -sha256 -inform pem -in <(bosh interpolate state/cf-deployment-vars.yml --path $certificate_authority))
    echo $fingerprint $common_name $certificate_authority
done